# Generated by Django 2.0.1 on 2019-02-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adplayer', '0002_remove_impression_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adplayer.Playlist'),
            preserve_default=False,
        ),
    ]
