# Generated by Django 2.0.1 on 2019-02-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('url', models.URLField(unique=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adplayer.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='impression',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adplayer.Player'),
        ),
        migrations.AddField(
            model_name='impression',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adplayer.Playlist'),
        ),
        migrations.AddField(
            model_name='impression',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adplayer.Video'),
        ),
    ]
